// Semantic app version — the single source of truth, displayed on the hub.
// Bump it whenever any cached file changes: it triggers a fresh re-download
// of everything in ASSETS on the next online visit.
const CACHE = 'offline-games-0.5.25';

const ASSETS = [
  './',
  './index.html',
  './sw.js', // cached so the hub can read the version offline
  './app-nav.js', // history-replace navigation (kills iOS edge-swipe back/forward) — on every page
  './manifest.webmanifest',
  './icons/icon-180.png',
  './icons/icon-512.png',
  './games/pad-test/',
  './games/pad-test/index.html',
  './games/gba/',
  './games/gba/index.html',
  './games/nds/',
  './games/nds/index.html',
  './games/mahjong-tianjin/',
  './games/mahjong-tianjin/index.html',
  './games/mahjong-tianjin/board.css',
  './games/mahjong-tianjin/engine.js',
  './games/mahjong-tianjin/ai.js',
  './games/mahjong-tianjin/backend.js',
  './games/mahjong-common/remote-backend.js',
  './games/mahjong-tianjin/main.js',
  './games/mahjong-tianjin/scene.js',
  './games/mahjong-tianjin/scene2d.js',
  './games/mahjong-tianjin/sound.js',
  './games/mahjong-tianjin/handorder.js',
  './games/mahjong-tianjin/ui-util.js',
  './games/mahjong-tianjin/lib/three.module.min.js',
  './games/mahjong-tianjin/textures/felt_color.jpg',
  './games/mahjong-tianjin/textures/felt_normal.jpg',
  './games/mahjong-tianjin/textures/felt_rough.jpg',
  './games/mahjong-tianjin/textures/wood_color.jpg',
  './games/mahjong-tianjin/textures/wood_normal.jpg',
  './games/mahjong-tianjin/textures/wood_rough.jpg',
  './games/mahjong-tianjin/sounds/pung.wav',
  './games/mahjong-tianjin/sounds/chow.wav',
  './games/mahjong-tianjin/sounds/kong.wav',
  './games/mahjong-tianjin/tiles/Man1.png',
  './games/mahjong-tianjin/tiles/Man2.png',
  './games/mahjong-tianjin/tiles/Man3.png',
  './games/mahjong-tianjin/tiles/Man4.png',
  './games/mahjong-tianjin/tiles/Man5.png',
  './games/mahjong-tianjin/tiles/Man6.png',
  './games/mahjong-tianjin/tiles/Man7.png',
  './games/mahjong-tianjin/tiles/Man8.png',
  './games/mahjong-tianjin/tiles/Man9.png',
  './games/mahjong-tianjin/tiles/Pin1.png',
  './games/mahjong-tianjin/tiles/Pin2.png',
  './games/mahjong-tianjin/tiles/Pin3.png',
  './games/mahjong-tianjin/tiles/Pin4.png',
  './games/mahjong-tianjin/tiles/Pin5.png',
  './games/mahjong-tianjin/tiles/Pin6.png',
  './games/mahjong-tianjin/tiles/Pin7.png',
  './games/mahjong-tianjin/tiles/Pin8.png',
  './games/mahjong-tianjin/tiles/Pin9.png',
  './games/mahjong-tianjin/tiles/Sou1.png',
  './games/mahjong-tianjin/tiles/Sou2.png',
  './games/mahjong-tianjin/tiles/Sou3.png',
  './games/mahjong-tianjin/tiles/Sou4.png',
  './games/mahjong-tianjin/tiles/Sou5.png',
  './games/mahjong-tianjin/tiles/Sou6.png',
  './games/mahjong-tianjin/tiles/Sou7.png',
  './games/mahjong-tianjin/tiles/Sou8.png',
  './games/mahjong-tianjin/tiles/Sou9.png',
  './games/mahjong-tianjin/tiles/Ton.png',
  './games/mahjong-tianjin/tiles/Nan.png',
  './games/mahjong-tianjin/tiles/Shaa.png',
  './games/mahjong-tianjin/tiles/Pei.png',
  './games/mahjong-tianjin/tiles/Chun.png',
  './games/mahjong-tianjin/tiles/Hatsu.png',
  './games/mahjong-tianjin/tiles/Haku.png',
  './games/mahjong-common/voice/0/ankong.wav',
  './games/mahjong-common/voice/0/chi.wav',
  './games/mahjong-common/voice/0/d0.wav',
  './games/mahjong-common/voice/0/d1.wav',
  './games/mahjong-common/voice/0/d2.wav',
  './games/mahjong-common/voice/0/dianpao.wav',
  './games/mahjong-common/voice/0/hula.wav',
  './games/mahjong-common/voice/0/jinkong.wav',
  './games/mahjong-common/voice/0/m1.wav',
  './games/mahjong-common/voice/0/m2.wav',
  './games/mahjong-common/voice/0/m3.wav',
  './games/mahjong-common/voice/0/m4.wav',
  './games/mahjong-common/voice/0/m5.wav',
  './games/mahjong-common/voice/0/m6.wav',
  './games/mahjong-common/voice/0/m7.wav',
  './games/mahjong-common/voice/0/m8.wav',
  './games/mahjong-common/voice/0/m9.wav',
  './games/mahjong-common/voice/0/mingkong.wav',
  './games/mahjong-common/voice/0/p1.wav',
  './games/mahjong-common/voice/0/p2.wav',
  './games/mahjong-common/voice/0/p3.wav',
  './games/mahjong-common/voice/0/p4.wav',
  './games/mahjong-common/voice/0/p5.wav',
  './games/mahjong-common/voice/0/p6.wav',
  './games/mahjong-common/voice/0/p7.wav',
  './games/mahjong-common/voice/0/p8.wav',
  './games/mahjong-common/voice/0/p9.wav',
  './games/mahjong-common/voice/0/pung.wav',
  './games/mahjong-common/voice/0/s1.wav',
  './games/mahjong-common/voice/0/s2.wav',
  './games/mahjong-common/voice/0/s3.wav',
  './games/mahjong-common/voice/0/s4.wav',
  './games/mahjong-common/voice/0/s5.wav',
  './games/mahjong-common/voice/0/s6.wav',
  './games/mahjong-common/voice/0/s7.wav',
  './games/mahjong-common/voice/0/s8.wav',
  './games/mahjong-common/voice/0/s9.wav',
  './games/mahjong-common/voice/0/w0.wav',
  './games/mahjong-common/voice/0/w1.wav',
  './games/mahjong-common/voice/0/w2.wav',
  './games/mahjong-common/voice/0/w3.wav',
  './games/mahjong-common/voice/0/zimo.wav',
  './games/mahjong-common/voice/1/ankong.wav',
  './games/mahjong-common/voice/1/chi.wav',
  './games/mahjong-common/voice/1/d0.wav',
  './games/mahjong-common/voice/1/d1.wav',
  './games/mahjong-common/voice/1/d2.wav',
  './games/mahjong-common/voice/1/dianpao.wav',
  './games/mahjong-common/voice/1/hula.wav',
  './games/mahjong-common/voice/1/jinkong.wav',
  './games/mahjong-common/voice/1/m1.wav',
  './games/mahjong-common/voice/1/m2.wav',
  './games/mahjong-common/voice/1/m3.wav',
  './games/mahjong-common/voice/1/m4.wav',
  './games/mahjong-common/voice/1/m5.wav',
  './games/mahjong-common/voice/1/m6.wav',
  './games/mahjong-common/voice/1/m7.wav',
  './games/mahjong-common/voice/1/m8.wav',
  './games/mahjong-common/voice/1/m9.wav',
  './games/mahjong-common/voice/1/mingkong.wav',
  './games/mahjong-common/voice/1/p1.wav',
  './games/mahjong-common/voice/1/p2.wav',
  './games/mahjong-common/voice/1/p3.wav',
  './games/mahjong-common/voice/1/p4.wav',
  './games/mahjong-common/voice/1/p5.wav',
  './games/mahjong-common/voice/1/p6.wav',
  './games/mahjong-common/voice/1/p7.wav',
  './games/mahjong-common/voice/1/p8.wav',
  './games/mahjong-common/voice/1/p9.wav',
  './games/mahjong-common/voice/1/pung.wav',
  './games/mahjong-common/voice/1/s1.wav',
  './games/mahjong-common/voice/1/s2.wav',
  './games/mahjong-common/voice/1/s3.wav',
  './games/mahjong-common/voice/1/s4.wav',
  './games/mahjong-common/voice/1/s5.wav',
  './games/mahjong-common/voice/1/s6.wav',
  './games/mahjong-common/voice/1/s7.wav',
  './games/mahjong-common/voice/1/s8.wav',
  './games/mahjong-common/voice/1/s9.wav',
  './games/mahjong-common/voice/1/w0.wav',
  './games/mahjong-common/voice/1/w1.wav',
  './games/mahjong-common/voice/1/w2.wav',
  './games/mahjong-common/voice/1/w3.wav',
  './games/mahjong-common/voice/1/zimo.wav',
  './games/mahjong-common/voice/2/ankong.wav',
  './games/mahjong-common/voice/2/chi.wav',
  './games/mahjong-common/voice/2/d0.wav',
  './games/mahjong-common/voice/2/d1.wav',
  './games/mahjong-common/voice/2/d2.wav',
  './games/mahjong-common/voice/2/dianpao.wav',
  './games/mahjong-common/voice/2/hula.wav',
  './games/mahjong-common/voice/2/jinkong.wav',
  './games/mahjong-common/voice/2/m1.wav',
  './games/mahjong-common/voice/2/m2.wav',
  './games/mahjong-common/voice/2/m3.wav',
  './games/mahjong-common/voice/2/m4.wav',
  './games/mahjong-common/voice/2/m5.wav',
  './games/mahjong-common/voice/2/m6.wav',
  './games/mahjong-common/voice/2/m7.wav',
  './games/mahjong-common/voice/2/m8.wav',
  './games/mahjong-common/voice/2/m9.wav',
  './games/mahjong-common/voice/2/mingkong.wav',
  './games/mahjong-common/voice/2/p1.wav',
  './games/mahjong-common/voice/2/p2.wav',
  './games/mahjong-common/voice/2/p3.wav',
  './games/mahjong-common/voice/2/p4.wav',
  './games/mahjong-common/voice/2/p5.wav',
  './games/mahjong-common/voice/2/p6.wav',
  './games/mahjong-common/voice/2/p7.wav',
  './games/mahjong-common/voice/2/p8.wav',
  './games/mahjong-common/voice/2/p9.wav',
  './games/mahjong-common/voice/2/pung.wav',
  './games/mahjong-common/voice/2/s1.wav',
  './games/mahjong-common/voice/2/s2.wav',
  './games/mahjong-common/voice/2/s3.wav',
  './games/mahjong-common/voice/2/s4.wav',
  './games/mahjong-common/voice/2/s5.wav',
  './games/mahjong-common/voice/2/s6.wav',
  './games/mahjong-common/voice/2/s7.wav',
  './games/mahjong-common/voice/2/s8.wav',
  './games/mahjong-common/voice/2/s9.wav',
  './games/mahjong-common/voice/2/w0.wav',
  './games/mahjong-common/voice/2/w1.wav',
  './games/mahjong-common/voice/2/w2.wav',
  './games/mahjong-common/voice/2/w3.wav',
  './games/mahjong-common/voice/2/zimo.wav',
  './games/mahjong-common/voice/3/ankong.wav',
  './games/mahjong-common/voice/3/chi.wav',
  './games/mahjong-common/voice/3/d0.wav',
  './games/mahjong-common/voice/3/d1.wav',
  './games/mahjong-common/voice/3/d2.wav',
  './games/mahjong-common/voice/3/dianpao.wav',
  './games/mahjong-common/voice/3/hula.wav',
  './games/mahjong-common/voice/3/jinkong.wav',
  './games/mahjong-common/voice/3/m1.wav',
  './games/mahjong-common/voice/3/m2.wav',
  './games/mahjong-common/voice/3/m3.wav',
  './games/mahjong-common/voice/3/m4.wav',
  './games/mahjong-common/voice/3/m5.wav',
  './games/mahjong-common/voice/3/m6.wav',
  './games/mahjong-common/voice/3/m7.wav',
  './games/mahjong-common/voice/3/m8.wav',
  './games/mahjong-common/voice/3/m9.wav',
  './games/mahjong-common/voice/3/mingkong.wav',
  './games/mahjong-common/voice/3/p1.wav',
  './games/mahjong-common/voice/3/p2.wav',
  './games/mahjong-common/voice/3/p3.wav',
  './games/mahjong-common/voice/3/p4.wav',
  './games/mahjong-common/voice/3/p5.wav',
  './games/mahjong-common/voice/3/p6.wav',
  './games/mahjong-common/voice/3/p7.wav',
  './games/mahjong-common/voice/3/p8.wav',
  './games/mahjong-common/voice/3/p9.wav',
  './games/mahjong-common/voice/3/pung.wav',
  './games/mahjong-common/voice/3/s1.wav',
  './games/mahjong-common/voice/3/s2.wav',
  './games/mahjong-common/voice/3/s3.wav',
  './games/mahjong-common/voice/3/s4.wav',
  './games/mahjong-common/voice/3/s5.wav',
  './games/mahjong-common/voice/3/s6.wav',
  './games/mahjong-common/voice/3/s7.wav',
  './games/mahjong-common/voice/3/s8.wav',
  './games/mahjong-common/voice/3/s9.wav',
  './games/mahjong-common/voice/3/w0.wav',
  './games/mahjong-common/voice/3/w1.wav',
  './games/mahjong-common/voice/3/w2.wav',
  './games/mahjong-common/voice/3/w3.wav',
  './games/mahjong-common/voice/3/zimo.wav',
  './games/mahjong-common-online/',
  './games/mahjong-common-online/index.html',
  './games/mahjong-common-online/lobby.css',
  './games/mahjong-common-online/lobby.js',
  './games/guobiao/',
  './games/guobiao/index.html',
  './games/guobiao/guobiao.css',
  './games/guobiao/engine.js',
  './games/guobiao/score.js',
  './games/guobiao/ai.js',
  './games/guobiao/backend.js',
  './games/guobiao/main.js',
  './games/guobiao-free/',
  './games/guobiao-free/index.html',
  './games/doudizhu/',
  './games/doudizhu/index.html',
  './games/doudizhu/doudizhu.css',
  './games/doudizhu/engine.js',
  './games/doudizhu/ai.js',
  './games/doudizhu/backend.js',
  './games/doudizhu/scene.js',
  './games/doudizhu/scene2d.js',
  './games/doudizhu/select.js',
  './games/doudizhu/sound.js',
  './games/doudizhu/main.js',
  './games/doudizhu/voice/0/bid1.wav',
  './games/doudizhu/voice/0/bid2.wav',
  './games/doudizhu/voice/0/bid3.wav',
  './games/doudizhu/voice/0/bomb.wav',
  './games/doudizhu/voice/0/chuan.wav',
  './games/doudizhu/voice/0/dui10.wav',
  './games/doudizhu/voice/0/dui2.wav',
  './games/doudizhu/voice/0/dui3.wav',
  './games/doudizhu/voice/0/dui4.wav',
  './games/doudizhu/voice/0/dui5.wav',
  './games/doudizhu/voice/0/dui6.wav',
  './games/doudizhu/voice/0/dui7.wav',
  './games/doudizhu/voice/0/dui8.wav',
  './games/doudizhu/voice/0/dui9.wav',
  './games/doudizhu/voice/0/duiA.wav',
  './games/doudizhu/voice/0/duiJ.wav',
  './games/doudizhu/voice/0/duiK.wav',
  './games/doudizhu/voice/0/duiQ.wav',
  './games/doudizhu/voice/0/four2.wav',
  './games/doudizhu/voice/0/guo.wav',
  './games/doudizhu/voice/0/jokerB.wav',
  './games/doudizhu/voice/0/jokerS.wav',
  './games/doudizhu/voice/0/landlord.wav',
  './games/doudizhu/voice/0/plane.wav',
  './games/doudizhu/voice/0/r10.wav',
  './games/doudizhu/voice/0/r2.wav',
  './games/doudizhu/voice/0/r3.wav',
  './games/doudizhu/voice/0/r4.wav',
  './games/doudizhu/voice/0/r5.wav',
  './games/doudizhu/voice/0/r6.wav',
  './games/doudizhu/voice/0/r7.wav',
  './games/doudizhu/voice/0/r8.wav',
  './games/doudizhu/voice/0/r9.wav',
  './games/doudizhu/voice/0/rA.wav',
  './games/doudizhu/voice/0/rJ.wav',
  './games/doudizhu/voice/0/rK.wav',
  './games/doudizhu/voice/0/rQ.wav',
  './games/doudizhu/voice/0/rocket.wav',
  './games/doudizhu/voice/0/sa.wav',
  './games/doudizhu/voice/0/tri1.wav',
  './games/doudizhu/voice/0/tri2.wav',
  './games/doudizhu/voice/1/bid1.wav',
  './games/doudizhu/voice/1/bid2.wav',
  './games/doudizhu/voice/1/bid3.wav',
  './games/doudizhu/voice/1/bomb.wav',
  './games/doudizhu/voice/1/chuan.wav',
  './games/doudizhu/voice/1/dui10.wav',
  './games/doudizhu/voice/1/dui2.wav',
  './games/doudizhu/voice/1/dui3.wav',
  './games/doudizhu/voice/1/dui4.wav',
  './games/doudizhu/voice/1/dui5.wav',
  './games/doudizhu/voice/1/dui6.wav',
  './games/doudizhu/voice/1/dui7.wav',
  './games/doudizhu/voice/1/dui8.wav',
  './games/doudizhu/voice/1/dui9.wav',
  './games/doudizhu/voice/1/duiA.wav',
  './games/doudizhu/voice/1/duiJ.wav',
  './games/doudizhu/voice/1/duiK.wav',
  './games/doudizhu/voice/1/duiQ.wav',
  './games/doudizhu/voice/1/four2.wav',
  './games/doudizhu/voice/1/guo.wav',
  './games/doudizhu/voice/1/jokerB.wav',
  './games/doudizhu/voice/1/jokerS.wav',
  './games/doudizhu/voice/1/landlord.wav',
  './games/doudizhu/voice/1/plane.wav',
  './games/doudizhu/voice/1/r10.wav',
  './games/doudizhu/voice/1/r2.wav',
  './games/doudizhu/voice/1/r3.wav',
  './games/doudizhu/voice/1/r4.wav',
  './games/doudizhu/voice/1/r5.wav',
  './games/doudizhu/voice/1/r6.wav',
  './games/doudizhu/voice/1/r7.wav',
  './games/doudizhu/voice/1/r8.wav',
  './games/doudizhu/voice/1/r9.wav',
  './games/doudizhu/voice/1/rA.wav',
  './games/doudizhu/voice/1/rJ.wav',
  './games/doudizhu/voice/1/rK.wav',
  './games/doudizhu/voice/1/rQ.wav',
  './games/doudizhu/voice/1/rocket.wav',
  './games/doudizhu/voice/1/sa.wav',
  './games/doudizhu/voice/1/tri1.wav',
  './games/doudizhu/voice/1/tri2.wav',
  './games/doudizhu/voice/2/bid1.wav',
  './games/doudizhu/voice/2/bid2.wav',
  './games/doudizhu/voice/2/bid3.wav',
  './games/doudizhu/voice/2/bomb.wav',
  './games/doudizhu/voice/2/chuan.wav',
  './games/doudizhu/voice/2/dui10.wav',
  './games/doudizhu/voice/2/dui2.wav',
  './games/doudizhu/voice/2/dui3.wav',
  './games/doudizhu/voice/2/dui4.wav',
  './games/doudizhu/voice/2/dui5.wav',
  './games/doudizhu/voice/2/dui6.wav',
  './games/doudizhu/voice/2/dui7.wav',
  './games/doudizhu/voice/2/dui8.wav',
  './games/doudizhu/voice/2/dui9.wav',
  './games/doudizhu/voice/2/duiA.wav',
  './games/doudizhu/voice/2/duiJ.wav',
  './games/doudizhu/voice/2/duiK.wav',
  './games/doudizhu/voice/2/duiQ.wav',
  './games/doudizhu/voice/2/four2.wav',
  './games/doudizhu/voice/2/guo.wav',
  './games/doudizhu/voice/2/jokerB.wav',
  './games/doudizhu/voice/2/jokerS.wav',
  './games/doudizhu/voice/2/landlord.wav',
  './games/doudizhu/voice/2/plane.wav',
  './games/doudizhu/voice/2/r10.wav',
  './games/doudizhu/voice/2/r2.wav',
  './games/doudizhu/voice/2/r3.wav',
  './games/doudizhu/voice/2/r4.wav',
  './games/doudizhu/voice/2/r5.wav',
  './games/doudizhu/voice/2/r6.wav',
  './games/doudizhu/voice/2/r7.wav',
  './games/doudizhu/voice/2/r8.wav',
  './games/doudizhu/voice/2/r9.wav',
  './games/doudizhu/voice/2/rA.wav',
  './games/doudizhu/voice/2/rJ.wav',
  './games/doudizhu/voice/2/rK.wav',
  './games/doudizhu/voice/2/rQ.wav',
  './games/doudizhu/voice/2/rocket.wav',
  './games/doudizhu/voice/2/sa.wav',
  './games/doudizhu/voice/2/tri1.wav',
  './games/doudizhu/voice/2/tri2.wav',
  './shared/emu-persistence.js',
  './emulatorjs/data/emulator.css',
  './emulatorjs/data/loader.js',
  './emulatorjs/data/version.json',
  './emulatorjs/data/compression/extract7z.js',
  './emulatorjs/data/compression/extractzip.js',
  './emulatorjs/data/compression/libunrar.js',
  './emulatorjs/data/compression/libunrar.wasm',
  './emulatorjs/data/cores/mgba-legacy-wasm.data',
  './emulatorjs/data/cores/mgba-wasm.data',
  './emulatorjs/data/cores/melonds-legacy-wasm.data',
  './emulatorjs/data/cores/melonds-wasm.data',
  './emulatorjs/data/cores/melonds-thread-legacy-wasm.data',
  './emulatorjs/data/cores/melonds-thread-wasm.data',
  './emulatorjs/data/cores/vbam-wasm.data',
  './emulatorjs/data/cores/vbam-legacy-wasm.data',
  './emulatorjs/data/cores/reports/mgba.json',
  './emulatorjs/data/cores/reports/melonds.json',
  './emulatorjs/data/cores/reports/vbam.json',
  './emulatorjs/data/localization/af-FR.json',
  './emulatorjs/data/localization/ar-AR.json',
  './emulatorjs/data/localization/ben-BEN.json',
  './emulatorjs/data/localization/de-GER.json',
  './emulatorjs/data/localization/el-GR.json',
  './emulatorjs/data/localization/en-US.json',
  './emulatorjs/data/localization/es-ES.json',
  './emulatorjs/data/localization/fa-AF.json',
  './emulatorjs/data/localization/hi-HI.json',
  './emulatorjs/data/localization/it-IT.json',
  './emulatorjs/data/localization/ja-JA.json',
  './emulatorjs/data/localization/jv-JV.json',
  './emulatorjs/data/localization/ko-KO.json',
  './emulatorjs/data/localization/pt-BR.json',
  './emulatorjs/data/localization/retroarch.json',
  './emulatorjs/data/localization/ro-RO.json',
  './emulatorjs/data/localization/ru-RU.json',
  './emulatorjs/data/localization/tr-TR.json',
  './emulatorjs/data/localization/vi-VN.json',
  './emulatorjs/data/localization/zh-CN.json',
  './emulatorjs/data/src/compression.js',
  './emulatorjs/data/src/emulator.js',
  './emulatorjs/data/src/GameManager.js',
  './emulatorjs/data/src/gamepad.js',
  './emulatorjs/data/src/nipplejs.js',
  './emulatorjs/data/src/shaders.js',
  './emulatorjs/data/src/socket.io.min.js',
  './emulatorjs/data/src/storage.js',
];

// Post a message to every window of this origin — including ones not yet
// controlled by this worker (the hub that triggered the update is controlled by
// the OLD worker while we install), so the progress bar can be driven live.
function broadcast(msg) {
  return self.clients.matchAll({ includeUncontrolled: true, type: 'window' })
    .then((clients) => clients.forEach((c) => c.postMessage(msg)));
}

self.addEventListener('install', (e) => {
  e.waitUntil((async () => {
    const cache = await caches.open(CACHE);
    const total = ASSETS.length;
    let done = 0, lastPct = -1;
    // Report progress only when the whole-number percent changes (≤101 messages,
    // not one per asset). Fire-and-forget — progress is best-effort cosmetics.
    const tick = () => {
      const pct = Math.floor((done / total) * 100);
      if (pct !== lastPct) { lastPct = pct; broadcast({ type: 'install-progress', done, total, pct }); }
    };
    tick();
    // Per-asset cache.add (instead of cache.addAll) so we can count completions.
    // Promise.all still rejects on any failure, so a broken asset fails the whole
    // install exactly like addAll did — the cache never ends up half-populated.
    await Promise.all(ASSETS.map((url) => cache.add(url).then(() => { done++; tick(); })));
    await self.skipWaiting();
  })());
});

self.addEventListener('activate', (e) => {
  e.waitUntil(
    caches.keys()
      .then((keys) => Promise.all(keys.filter((k) => k !== CACHE).map((k) => caches.delete(k))))
      .then(() => self.clients.claim())
  );
});

// Report the running version (the cache name carries it) when the hub asks — so the
// page can show the version of the worker that is actually in control, not a stale
// cached copy of sw.js.
self.addEventListener('message', (e) => {
  if (e.data === 'version' && e.ports[0]) e.ports[0].postMessage(CACHE);
  // Let the hub force a worker that's stuck waiting (e.g. one left by an older
  // sw.js without skipWaiting) to activate so the update can finish.
  else if (e.data === 'skipWaiting') self.skipWaiting();
});

// Re-emit a response with the headers that enable cross-origin isolation
// (crossOriginIsolated === true → SharedArrayBuffer works → threaded cores).
// GitHub Pages can't set these, so the service worker adds them. All our
// assets are same-origin, so COEP: require-corp is satisfied.
function crossOriginIsolate(res) {
  const headers = new Headers(res.headers);
  headers.set('Cross-Origin-Opener-Policy', 'same-origin');
  headers.set('Cross-Origin-Embedder-Policy', 'require-corp');
  headers.set('Cross-Origin-Resource-Policy', 'same-origin');
  return new Response(res.body, { status: res.status, statusText: res.statusText, headers });
}

// Cache-first: guarantees offline play; new versions arrive via the
// version bump above, never silently mid-session.
self.addEventListener('fetch', (e) => {
  if (e.request.method !== 'GET') return;
  e.respondWith(
    caches.match(e.request, { ignoreSearch: true }).then((hit) => {
      if (hit) return crossOriginIsolate(hit);
      return fetch(e.request).then((res) => {
        if (res.ok && new URL(e.request.url).origin === location.origin) {
          const copy = res.clone();
          caches.open(CACHE).then((cache) => cache.put(e.request, copy));
        }
        return crossOriginIsolate(res);
      });
    })
  );
});
