// Generate the SUB-HUB service workers (sw-<name>.js at the repo root, git-ignored) from sw.js.
//
// A sub-hub is a shareable, scoped entry to a SUBSET of the site (e.g. /mj/ = 天津麻将 only) that
// still lives on the same origin. Because the whole site is plain ES modules, code is already
// split per game — a page only ever loads its own import graph. The only two artifacts that span
// everything are the hub page and the service worker's precache list, so a sub-hub is just:
//   1. a small landing page (committed, e.g. mj/index.html) that plants the hub-home marker
//      (shared/hub-home.js) and registers its own service worker, and
//   2. THIS generator's output: sw.js verbatim, with only two substitutions — the CACHE name
//      (`<cache>-<version>`, version inherited from sw.js so one bump versions everything) and
//      the ASSETS array filtered to the profile's path prefixes. All update/offline/COOP logic
//      stays identical.
//
// Profiles live in tools/subhubs.json:
//   { "<name>": { "cache": "...", "extra": ["./<name>/", ...], "prefixes": ["./games/x/", ...] } }
// Adding a future partial hub = one profile entry + one landing folder. Run this after changing
// sw.js ASSETS or a profile; tools/deploy-azure.ps1 runs it on every deploy. Zero dependencies.
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const profiles = JSON.parse(fs.readFileSync(path.join(ROOT, 'tools', 'subhubs.json'), 'utf8'));
const sw = fs.readFileSync(path.join(ROOT, 'sw.js'), 'utf8');

const ver = sw.match(/offline-games-([0-9.]+)/)?.[1];
if (!ver) throw new Error('could not read the CACHE version from sw.js');
const arr = sw.match(/const ASSETS = \[([\s\S]*?)\n\];/);
if (!arr) throw new Error('could not locate the ASSETS array in sw.js');
const entries = [...arr[1].matchAll(/'(\.\/[^']*)'/g)].map((m) => m[1]);

// The content-versioned media list is filtered by the SAME prefixes, so a sub-hub pulls only its own
// artwork and voice — out of the one shared MEDIA_CACHE, which means anything the full hub already
// fetched (mahjong-common's voice sprites) is not fetched again here.
const med = sw.match(/const MEDIA = \[([\s\S]*?)\n\];/);
if (!med) throw new Error('could not locate the MEDIA array in sw.js');
const media = [...med[1].matchAll(/'(\.\/[^']*)'/g)].map((m) => m[1]);

for (const [name, p] of Object.entries(profiles)) {
  const inProfile = (e) => p.prefixes.some((x) => e === x || e.startsWith(x));
  const keep = entries.filter(inProfile);
  const assets = [...(p.extra || []), ...keep];
  const keepMedia = media.filter(inProfile);
  const missing = p.prefixes.filter((x) => ![...entries, ...media].some((e) => e === x || e.startsWith(x)));
  if (missing.length) console.warn(`  WARN [${name}]: prefixes matching nothing in sw.js: ${missing.join(', ')}`);
  let out = sw
    .replace(/const CACHE = '[^']+';/, `const CACHE = '${p.cache}-${ver}';`)
    .replace(arr[0], `const ASSETS = [\n${assets.map((a) => `  '${a}',`).join('\n')}\n];`)
    .replace(med[0], `const MEDIA = [\n${keepMedia.map((a) => `  '${a}',`).join('\n')}\n];`);
  out = `// GENERATED by tools/gen-subhub.js from sw.js — DO NOT EDIT (profile '${name}' in tools/subhubs.json)\n${out}`;
  fs.writeFileSync(path.join(ROOT, `sw-${name}.js`), out);
  console.log(`sw-${name}.js: ${assets.length} assets (of ${entries.length}) + ${keepMedia.length} media (of ${media.length}), cache ${p.cache}-${ver}`);
}
