// Audio for 掼蛋: procedural Web-Audio SFX + spoken announcements.
//
// Voice uses PRE-RENDERED neural-TTS clips (generated by the sibling voiceAIGeneration repo, bundled
// for offline play) — one distinct voice per seat (0 你 / 1 右家 / 2 对家 / 3 左家), the same 4-persona
// cast as the mahjong games. main.js passes token ARRAYS to speak() (e.g. ['俩九'], ['钢板！']); the
// SLUG map below resolves each token to a clip. Combo callouts (炸弹！/钢板！/三连对！/同花顺！/顺子！…)
// are dedicated clips; singles/pairs/trips are 五 / 俩五 / 仨五. If the clips aren't bundled yet (or a
// token has no clip — 不要 / 头游 …), speak() falls back to the device's SpeechSynthesis, so there's
// always a voice.
let ctx = null;
let muted = false;
const USE_CLIPS = true;
const seatPitch = [1.0, 1.14, 0.92, 1.06]; // fallback-TTS pitch per seat (clips already differ by voice)

export function setMuted(m) { muted = !!m; }
export function isMuted() { return muted; }
export function resume() {
  try { if (!ctx) ctx = new (window.AudioContext || window.webkitAudioContext)(); if (ctx.state === 'suspended') ctx.resume(); } catch {}
  primeVoices();
  if (!muted) preload();
}

function blip(freq, dur, type = 'sine', gain = 0.18) {
  if (muted) return;
  try {
    if (!ctx) ctx = new (window.AudioContext || window.webkitAudioContext)();
    const o = ctx.createOscillator(), g = ctx.createGain();
    o.type = type; o.frequency.value = freq;
    g.gain.setValueAtTime(gain, ctx.currentTime);
    g.gain.exponentialRampToValueAtTime(0.0001, ctx.currentTime + dur);
    o.connect(g).connect(ctx.destination); o.start(); o.stop(ctx.currentTime + dur);
  } catch {}
}

export const sfx = {
  play() { blip(440, 0.09, 'triangle', 0.14); blip(680, 0.07, 'triangle', 0.08); },
  pass() { blip(240, 0.12, 'sine', 0.10); },
  bomb() { blip(140, 0.5, 'sawtooth', 0.26); setTimeout(() => blip(90, 0.4, 'sawtooth', 0.2), 60); },
  flush() { blip(520, 0.18, 'triangle', 0.16); setTimeout(() => blip(780, 0.2, 'triangle', 0.12), 70); },
  win() { [523, 659, 784, 1047].forEach((f, i) => setTimeout(() => blip(f, 0.22, 'triangle', 0.16), i * 110)); },
  lose() { [392, 330, 262].forEach((f, i) => setTimeout(() => blip(f, 0.26, 'sine', 0.14), i * 130)); },
  deal() { blip(520, 0.05, 'triangle', 0.08); },
  tribute() { blip(360, 0.16, 'sine', 0.12); setTimeout(() => blip(300, 0.16, 'sine', 0.1), 120); },
};

// ---- voice clips -----------------------------------------------------------
const VOICE_BASE = new URL('./voice/', import.meta.url).href;
// token text -> filename slug (kept in sync with the sibling gen-voice-oss.py VOCAB_GUANDAN)
const _R = { '三': 'r3', '四': 'r4', '五': 'r5', '六': 'r6', '七': 'r7', '八': 'r8', '九': 'r9', '十': 'r10', '勾': 'rJ', '圈': 'rQ', 'K': 'rK', '尖': 'rA', '二': 'r2' };
const _LBL = ['3', '4', '5', '6', '7', '8', '9', '10', 'J', 'Q', 'K', 'A', '2'];
const SLUG = {
  ..._R, '小王': 'jokerS', '大王': 'jokerB',
  ...Object.fromEntries(_LBL.map((l, i) => ['俩' + Object.keys(_R)[i], 'dui' + l])), // 对子: 俩X
  ...Object.fromEntries(_LBL.map((l, i) => ['仨' + Object.keys(_R)[i], 'sa' + l])),  // 三同张: 仨X
  '三带二！': 'tri2', '顺子！': 'shunzi', '钢板！': 'tube', '三连对！': 'plate',
  '同花顺！': 'flush', '炸弹！': 'bomb', '王炸！': 'rocket',
};

const buffers = [{}, {}, {}, {}]; // buffers[seat][slug] = { buf, offset, duration }
let loaded = false, loading = false;
let activeSources = [];

function decode(ab) {
  return new Promise((res, rej) => { const p = ctx.decodeAudioData(ab, res, rej); if (p && p.then) p.then(res, rej); });
}
// Speech region of a decoded clip, ignoring leading/trailing near-silence (gapless concatenation).
function speechRegion(buf) {
  const d = buf.getChannelData(0), n = d.length, sr = buf.sampleRate, thr = 0.012;
  let s = 0, e = n - 1;
  while (s < n && Math.abs(d[s]) < thr) s++;
  while (e > s && Math.abs(d[e]) < thr) e--;
  const pad = Math.floor(sr * 0.006);
  s = Math.max(0, s - pad); e = Math.min(n - 1, e + pad);
  return { buf, offset: s / sr, duration: Math.max(0.04, (e - s) / sr) };
}
async function preload() {
  if (!USE_CLIPS || loaded || loading || !ctx) return;
  loading = true;
  try {
    // Preferred: one decoded "sprite" per seat + a slug->{offset,duration} manifest (tools/pack-voice.js).
    const manifest = await fetch(`${VOICE_BASE}packed/manifest.json`).then((r) => (r.ok ? r.json() : Promise.reject()));
    await Promise.all(Object.keys(manifest).map((seat) =>
      fetch(`${VOICE_BASE}packed/${seat}.wav`).then((r) => r.arrayBuffer()).then(decode)
        .then((buf) => { for (const slug in manifest[seat]) { const m = manifest[seat][slug]; buffers[seat][slug] = { buf, offset: m.offset, duration: m.duration }; } })));
    loaded = true; loading = false;
    return;
  } catch {}
  // Fallback: fetch + trim each clip (unpacked local dev, or no sprites yet).
  const slugs = [...new Set(Object.values(SLUG))];
  const jobs = [];
  for (let seat = 0; seat < 4; seat++) for (const slug of slugs) {
    jobs.push(fetch(`${VOICE_BASE}${seat}/${slug}.wav`).then((r) => (r.ok ? r.arrayBuffer() : Promise.reject())).then(decode)
      .then((buf) => { buffers[seat][slug] = speechRegion(buf); }).catch(() => {}));
  }
  await Promise.all(jobs);
  loaded = true; loading = false;
}

function stopVoice() {
  for (const s of activeSources) { try { s.stop(); } catch {} }
  activeSources = [];
  try { if (window.speechSynthesis) speechSynthesis.cancel(); } catch {}
}

// Speak a sequence of tokens in `seat`'s voice. Plays the bundled clips when ready; else falls back to
// SpeechSynthesis. Returns the estimated duration (ms) so callers can wait for the call to finish.
export function speak(tokens, seat = 0) {
  if (muted || !tokens || !tokens.length) return 0;
  resume();
  stopVoice();
  const slugs = tokens.map((t) => SLUG[t]);
  const ready = USE_CLIPS && ctx && loaded && slugs.every((s) => s && buffers[seat][s]);
  if (ready) {
    const start = Math.max(ctx.currentTime, 0) + 0.02;
    let t = start, end = start;
    for (const s of slugs) {
      const clip = buffers[seat][s];
      const src = ctx.createBufferSource(); src.buffer = clip.buf;
      src.connect(ctx.destination); src.start(t, clip.offset, clip.duration);
      activeSources.push(src);
      end = t + clip.duration;
      t += clip.duration - 0.015; // a hair of overlap so syllables run together with no seam
    }
    return Math.round((end - ctx.currentTime) * 1000);
  }
  sayTTS(tokens.join(''), seat);
  return 240 + [...tokens.join('')].length * 200;
}

// ---- SpeechSynthesis fallback ----------------------------------------------
let voices = [];
function primeVoices() { try { voices = speechSynthesis.getVoices() || []; } catch {} }
try { if (window.speechSynthesis) { primeVoices(); speechSynthesis.onvoiceschanged = primeVoices; } } catch {}
function zhVoice() { return voices.find((v) => /zh|cmn|Chinese/i.test(v.lang + v.name)) || null; }
function sayTTS(text, seat = 0) {
  if (muted || !window.speechSynthesis) return;
  try {
    const u = new SpeechSynthesisUtterance(text);
    u.lang = 'zh-CN'; const v = zhVoice(); if (v) u.voice = v;
    u.pitch = seatPitch[seat] ?? 1.0; u.rate = 1.08;
    speechSynthesis.speak(u);
  } catch {}
}
